<a href="https://colab.research.google.com/github/Ginkno/postech-tech-challenge-fase2-grupo1-12dtat/blob/Elizabeth/notebooks/02_preprocessamento.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 02 — Pré-processamento

**Dimensão 4 da rúbrica — 15 pontos.**

Cada decisão precisa de justificativa escrita. Decidir *não* criar features é
aceitável, desde que o motivo esteja explícito.

In [29]:
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

# Semente fixa: use em TODO ponto com aleatoriedade (split, modelos, CV).
RANDOM_STATE = 42

RAW_1 = Path("/content") / "data" / "raw" / "application_record.csv"
RAW_2 = Path("/content") / "data" / "raw" / "credit_record.csv"

PROCESSED = Path("..") / "data" / "processed"
TARGET = "IS_BAD_PAYER"


pd.set_option("display.max_columns", None)

In [2]:
#Leitura do dataframe e visualização das cinco primeiras linhas.

df_application = pd.read_csv(RAW_1)
df_application.head()

,ID,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,DAYS_BIRTH,DAYS_EMPLOYED,FLAG_MOBIL,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS
0,5008804,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2.0
1,5008805,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2.0
2,5008806,M,Y,Y,0,112500.0,Working,Secondary / secondary special,Married,House / apartment,-21474,-1134,1,0,0,0,Security staff,2.0
3,5008808,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,-19110,-3051,1,0,1,1,Sales staff,1.0
4,5008809,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,-19110,-3051,1,0,1,1,Sales staff,1.0

## 1. Dados faltantes

In [3]:
#Verificando a existência de dados nulos.

df_application.isnull().sum()

ID                          0
CODE_GENDER                 0
FLAG_OWN_CAR                0
FLAG_OWN_REALTY             0
CNT_CHILDREN                0
AMT_INCOME_TOTAL            0
NAME_INCOME_TYPE            0
NAME_EDUCATION_TYPE         0
NAME_FAMILY_STATUS          0
NAME_HOUSING_TYPE           0
DAYS_BIRTH                  0
DAYS_EMPLOYED               0
FLAG_MOBIL                  0
FLAG_WORK_PHONE             0
FLAG_PHONE                  0
FLAG_EMAIL                  0
OCCUPATION_TYPE        134203
CNT_FAM_MEMBERS             0
dtype: int64

Verificando a existência de dados nulos e como resultado trouxe que a coluna OCCUPATION_TYPE possui 134203 linhas em branco.

In [4]:
#Substituir os dados em branco da variável OCCUPATION_TYPE por "Unknown".

df_application["OCCUPATION_TYPE"] = df_application["OCCUPATION_TYPE"].fillna("Unknown")

**Decisão:** Para que não haja dados em branco na coluna OCCUPATION_TYPE substituímos por 'Unknow'.

In [5]:
#Converter dias de nascimento para idade em anos e para inteiro.
df_application["YEARS_BIRTH"] = (df_application["DAYS_BIRTH"] / -365).astype(int)

#Criar a coluna IS_INACTIVE (1 para inativo, 0 para empregado).
df_application["IS_INACTIVE"] = (df_application["DAYS_EMPLOYED"] == 365243).astype(int)

#Converter dias de emprego para anos.
df_application["YEARS_EMPLOYED"] = (df_application["DAYS_EMPLOYED"] / -365 ).astype(int)

In [6]:
# Contar quantas vezes o valor -1000 aparece em YEARS_EMPLOYED
count_minus_1000 = (df_application['YEARS_EMPLOYED'] == -1000).sum()
print(f"Quantidade de registros com YEARS_EMPLOYED == -1000: {count_minus_1000}")

# Verificar a relação entre YEARS_EMPLOYED == -1000 e IS_INACTIVE
print("Verificando se -1000 em YEARS_EMPLOYED corresponde a IS_INACTIVE == 1:")
display(df_application.loc[df_application['YEARS_EMPLOYED'] == -1000, 'IS_INACTIVE'].value_counts())

Quantidade de registros com YEARS_EMPLOYED == -1000: 75329
Verificando se -1000 em YEARS_EMPLOYED corresponde a IS_INACTIVE == 1:

IS_INACTIVE
1    75329
Name: count, dtype: int64

Como esperado, o valor -1000 em YEARS_EMPLOYED corresponde exatamente aos registros onde IS_INACTIVE é 1, ou seja, aos 'pensionistas/inativos'. Para facilitar a análise e a modelagem, substituiremos esse valor por 0, indicando zero anos de emprego ativo, o que é consistente com a definição de inatividade.

In [7]:
# Substituir -1000 em YEARS_EMPLOYED por 0
df_application['YEARS_EMPLOYED'] = df_application['YEARS_EMPLOYED'].replace(-1000, 0)

# Verificar as primeiras linhas após a substituição
print("df_application.head() após substituição de -1000 por 0:")
display(df_application.head())

df_application.head() após substituição de -1000 por 0:

,ID,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,DAYS_BIRTH,DAYS_EMPLOYED,FLAG_MOBIL,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,YEARS_BIRTH,IS_INACTIVE,YEARS_EMPLOYED
0,5008804,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,Unknown,2.0,32,0,12
1,5008805,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,Unknown,2.0,32,0,12
2,5008806,M,Y,Y,0,112500.0,Working,Secondary / secondary special,Married,House / apartment,-21474,-1134,1,0,0,0,Security staff,2.0,58,0,3
3,5008808,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,-19110,-3051,1,0,1,1,Sales staff,1.0,52,0,8
4,5008809,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,-19110,-3051,1,0,1,1,Sales staff,1.0,52,0,8

In [8]:
df_application = df_application.drop(columns=['DAYS_BIRTH', 'DAYS_EMPLOYED'])
display(df_application.head())

,ID,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,FLAG_MOBIL,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,YEARS_BIRTH,IS_INACTIVE,YEARS_EMPLOYED
0,5008804,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,1,1,0,0,Unknown,2.0,32,0,12
1,5008805,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,1,1,0,0,Unknown,2.0,32,0,12
2,5008806,M,Y,Y,0,112500.0,Working,Secondary / secondary special,Married,House / apartment,1,0,0,0,Security staff,2.0,58,0,3
3,5008808,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,1,0,1,1,Sales staff,1.0,52,0,8
4,5008809,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,1,0,1,1,Sales staff,1.0,52,0,8

In [9]:
#Leitura do dataframe e visualização das cinco primeiras linhas.
df_credit = pd.read_csv(RAW_2)
df_credit.head()

        ID  MONTHS_BALANCE STATUS
0  5001711               0      X
1  5001711              -1      0
2  5001711              -2      0
3  5001711              -3      0
4  5001712               0      C

Conforme dicionário de dados disponibilizado: 0: 1-29 dias atrasados; 1: 30-59 dias atrasados; 2: 60-89 dias atrasados; 3: 90-119 dias atrasados; 4: 120-149 dias atrasados; 5: dívidas atrasadas ou incobráveis, perdas por mais de 150 dias; C: quitadas naquele mês; X: sem empréstimo no mês;

In [10]:
#Verificando a existência de dados nulos.

df_credit.isnull().sum()

ID                0
MONTHS_BALANCE    0
STATUS            0
dtype: int64

Como resultado trouxe que a quantidade de dados nulos é 0.

In [12]:
#Verificando a existência de dados duplicados.

df_credit.duplicated().sum()

np.int64(0)

In [13]:
print(df_credit['ID'].nunique())
print(len(df_credit))

45985
1048575

Para unir as informações de df_credit com as de df_application, é preciso consolidar o histórico de crédito de cada cliente (ID) em uma única linha.

Codificar a variável STATUS: Atribuir valores numéricos que reflitam o risco de crédito. Agregar por ID: Para cada cliente, obter a pontuação de risco máximo (pior status) e o número de meses no histórico (MONTHS_BALANCE). Criação de novas features.

In [14]:
# Criar uma cópia de df_credit para evitar modificar o original
df_status_history = df_credit.copy()

# Mapeamento de risco.
risk_mapping = {
    "C": 0,
    "X": -1,
    "0": 1, "1": 2, "2": 3, "3": 4, "4": 5, "5": 6
}
df_status_history["risk_score"] = df_status_history["STATUS"].map(risk_mapping)

# Consolidação do histórico de crédito.
# STATUS_LATED: 0 (1_29 dias) até o 5 (atraso grave).
# STATUS_ON_TIME: C (pago em dia).
# STATUS_NO_CREDIT: X (sem empréstimo no mês).

# Flags binárias para tipos de status.
df_status_history["is_lated"] = df_status_history["STATUS"].isin(["0","1", "2", "3", "4", "5"]).astype(int)
df_status_history["is_on_time"] = (df_status_history["STATUS"] == "C").astype(int)
df_status_history["is_no_credit"] = (df_status_history["STATUS"] == "X").astype(int)

# Agregação por ID.
df_status_aggregated = df_status_history.groupby("ID").agg(
    TOTAL_MONTHS_OBSERVED=("MONTHS_BALANCE", "count"),
    STATUS_LATED=("is_lated", "sum"),
    STATUS_ON_TIME=("is_on_time", "sum"),
    STATUS_NO_CREDIT=("is_no_credit", "sum"),
    MAX_RISK_SCORE=("risk_score", "max"),
    ).reset_index()

# Filtrar e agrupar o histórico recente (para os últimos 12 meses: 0 a -11)
df_recent_history = df_status_history[df_status_history['MONTHS_BALANCE'] >= -11].copy()
df_recent_aggregated = df_recent_history.groupby('ID').agg(
    TOTAL_MONTHS_RECENT=('MONTHS_BALANCE', 'count'),
    STATUS_LATED_RECENT=('is_lated', 'sum'),
    STATUS_ON_TIME_RECENT=("is_on_time", "sum"),
    STATUS_NO_CREDIT_RECENT=("is_no_credit", "sum"),
    MAX_RISK_SCORE_RECENT=('risk_score', 'max')
).reset_index()


# Filtrar e agrupar o histórico antigo (para meses mais antigos: antes de -11)
df_older_history = df_status_history[df_status_history['MONTHS_BALANCE'] < -11].copy()
df_older_aggregated = df_older_history.groupby('ID').agg(
    TOTAL_MONTHS_OLDER=('MONTHS_BALANCE', 'count'),
    STATUS_LATED_OLDER=('is_lated', 'sum'),
    STATUS_ON_TIME_OLDER=("is_on_time", "sum"),
    STATUS_NO_CREDIT_OLDER=("is_no_credit", "sum"),
    MAX_RISK_SCORE_OLDER=('risk_score', 'max')
).reset_index()


#Mesclagem dos históricos:
df_history_final = pd.merge(df_status_aggregated, df_recent_aggregated, on='ID', how='left')
df_history_final = pd.merge(df_history_final, df_older_aggregated, on='ID', how='left')

#Mesclagem do df_application com df_history_final.
df_merged = pd.merge(df_application, df_history_final, on='ID', how='inner')

print(f"Dimensão atual do df_merged: {df_merged.shape}")
display(df_merged.head(10))

Dimensão atual do df_merged: (36457, 34)

,ID,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,FLAG_MOBIL,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,YEARS_BIRTH,IS_INACTIVE,YEARS_EMPLOYED,TOTAL_MONTHS_OBSERVED,STATUS_LATED,STATUS_ON_TIME,STATUS_NO_CREDIT,MAX_RISK_SCORE,TOTAL_MONTHS_RECENT,STATUS_LATED_RECENT,STATUS_ON_TIME_RECENT,STATUS_NO_CREDIT_RECENT,MAX_RISK_SCORE_RECENT,TOTAL_MONTHS_OLDER,STATUS_LATED_OLDER,STATUS_ON_TIME_OLDER,STATUS_NO_CREDIT_OLDER,MAX_RISK_SCORE_OLDER
0,5008804,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,1,1,0,0,Unknown,2.0,32,0,12,16,2,13,1,2,12.0,0.0,12.0,0.0,0.0,4.0,2.0,1.0,1.0,2.0
1,5008805,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,1,1,0,0,Unknown,2.0,32,0,12,15,2,12,1,2,12.0,0.0,12.0,0.0,0.0,3.0,2.0,0.0,1.0,2.0
2,5008806,M,Y,Y,0,112500.0,Working,Secondary / secondary special,Married,House / apartment,1,0,0,0,Security staff,2.0,58,0,3,30,7,7,16,1,12.0,3.0,7.0,2.0,1.0,18.0,4.0,0.0,14.0,1.0
3,5008808,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,1,0,1,1,Sales staff,1.0,52,0,8,5,2,0,3,1,5.0,2.0,0.0,3.0,1.0,NaN,NaN,NaN,NaN,NaN
4,5008809,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,1,0,1,1,Sales staff,1.0,52,0,8,5,0,0,5,-1,NaN,NaN,NaN,NaN,NaN,5.0,0.0,0.0,5.0,-1.0
5,5008810,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,1,0,1,1,Sales staff,1.0,52,0,8,27,6,15,6,1,12.0,0.0,12.0,0.0,0.0,15.0,6.0,3.0,6.0,1.0
6,5008811,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,1,0,1,1,Sales staff,1.0,52,0,8,39,6,27,6,1,12.0,0.0,12.0,0.0,0.0,27.0,6.0,15.0,6.0,1.0
7,5008812,F,N,Y,0,283500.0,Pensioner,Higher education,Separated,House / apartment,1,0,0,0,Unknown,1.0,61,1,0,17,14,0,3,1,8.0,6.0,0.0,2.0,1.0,9.0,8.0,0.0,1.0,1.0
8,5008813,F,N,Y,0,283500.0,Pensioner,Higher education,Separated,House / apartment,1,0,0,0,Unknown,1.0,61,1,0,17,14,0,3,1,12.0,10.0,0.0,2.0,1.0,5.0,4.0,0.0,1.0,1.0
9,5008814,F,N,Y,0,283500.0,Pensioner,Higher education,Separated,House / apartment,1,0,0,0,Unknown,1.0,61,1,0,17,14,0,3,1,11.0,9.0,0.0,2.0,1.0,6.0,5.0,0.0,1.0,1.0

Criamos novas features que diferenciem a inadimplência recente da mais antiga. Isso pode capturar padrões de comportamento que a agregação total não revela, como uma melhora ou piora recente no comportamento de pagamento. Dividimos o histórico de crédito em dois períodos: os últimos 12 meses (de 0 a -11) e os meses anteriores (a partir de -12). União dos df_credit e df_application, com os IDs do df_credit contidos no df_application. Foi removido os 9528 IDs que não tinham variáveis de perfil no df_application, porque poderiam gerar ruídos graves.Preencher os dados faltantes artificialmente nas variáveis numéricas com a mediana e as categóricas com 'não informado', por exemplo, poedria criar padrões falsos.

In [15]:
# Preencher NaN para IDs que podem não ter histórico em um dos períodos
df_merged['TOTAL_MONTHS_RECENT'] = df_merged['TOTAL_MONTHS_RECENT'].fillna(0)
df_merged['STATUS_LATED_RECENT'] = df_merged['STATUS_LATED_RECENT'].fillna(0)
df_merged['STATUS_ON_TIME_RECENT'] = df_merged['STATUS_ON_TIME_RECENT'].fillna(0)
df_merged['STATUS_NO_CREDIT_RECENT'] = df_merged['STATUS_NO_CREDIT_RECENT'].fillna(0)
df_merged['MAX_RISK_SCORE_RECENT'] = df_merged['MAX_RISK_SCORE_RECENT'].fillna(-2) # -2 para indicar sem histórico ou sem risco neste período

df_merged['TOTAL_MONTHS_OLDER'] = df_merged['TOTAL_MONTHS_OLDER'].fillna(0)
df_merged['STATUS_LATED_OLDER'] = df_merged['STATUS_LATED_OLDER'].fillna(0)
df_merged['STATUS_ON_TIME_OLDER'] = df_merged['STATUS_ON_TIME_OLDER'].fillna(0)
df_merged['STATUS_NO_CREDIT_OLDER'] = df_merged['STATUS_NO_CREDIT_OLDER'].fillna(0)
df_merged['MAX_RISK_SCORE_OLDER'] = df_merged['MAX_RISK_SCORE_OLDER'].fillna(-2) # -2 para indicar sem histórico ou sem risco neste período

Ocorreram valores ausentes decorrentes da inexistência de registros em determinadas janelas de tempo, como esses casos não representam falhas de coleta, mas sim ausência de observações naquele período, os valores ausentes das variáveis de status foram substituídos por zero. Para as variáveis de pontuação de risco de crédito, utilizou-se o valor -2 para indicar explicitamente a ausência de histórico no período analisado.

In [16]:
df_final = df_merged.copy()
# Filtrar df_final para remover clientes que nunca pegaram empréstimo no período recente.
# Entendemos "nunca pegaram empréstimo" (STATUS_NO_CREDIT_RECENT = X) como aqueles clientes cujo pior status de risco
# foi MAX_RISK_SCORE_RECENT == -1.
df_final = df_final[df_final['MAX_RISK_SCORE_RECENT'] != -1].copy()

print(f"Dimensão do df_final após remover clientes sem histórico de empréstimo: {df_final.shape}")

Dimensão do df_final após remover clientes sem histórico de empréstimo: (32905, 34)

O dataset foi filtrado para excluir os clientes que nunca tiveram um empréstimo registrado. Esses clientes foram identificados pela condição de que seu MAX_RISK_SCORE fosse -1, o que indica que todos os seus registros de status de crédito foram 'X' (sem empréstimo). Esta filtragem garante que a análise e modelagem subsequentes se concentrem apenas em indivíduos que tiveram algum tipo de relacionamento com empréstimos. Já que não é possível classificar clientes sem histórico de crédito como bons ou maus pagadores.

## 2. Definição da variável alvo

_Se houve binarização, qual limiar e por quê? Justifique com base na distribuição, não por convenção._

Definição da Variável Alvo: IS_BAD_PAYER

A variável alvo IS_BAD_PAYER foi definida para identificar clientes que apresentaram um atraso de 60 dias ou mais (ou seja, risk_score igual ou superior a 3) em seu histórico de crédito durante os últimos 12 meses (MAX_RISK_SCORE_RECENT).

A utilização da janela recente busca capturar comportamentos mais representativos da condição atual do cliente, enquanto a exigência simultânea de atraso relevante e elevado risco reduz a classificação inadequada de clientes que apresentaram penas atrasos pontuais ou de baixa severidade.

IS_BAD_PAYER = 1 (Mau Pagador): Se o MAX_RISK_SCORE_RECENT for maior ou igual a 3 (o que corresponde a um atraso de 60-89 dias, ou mais grave, nos últimos 12 meses).

IS_BAD_PAYER = 0 (Bom Pagador): Caso contrário. Esta lógica foca na recência e na gravidade do atraso, o que pode ser um indicador mais relevante do risco de crédito atual de um cliente.

In [ ]:
# Definição da variável alvo IS_BAD_PAYER com base na lógica
# MAX_RISK_SCORE_RECENT >= 3 (equivalente a 60+ dias de atraso nos últimos 12 meses)
df_final['IS_BAD_PAYER'] = (df_final['MAX_RISK_SCORE_RECENT'] >= 3).astype(int)

print("Distribuição da variável alvo IS_BAD_PAYER:")
display(df_final['IS_BAD_PAYER'].value_counts(normalize=True).mul(100).round(2).astype(str) + '%')

# Visualizar a distribuição da variável alvo
plt.figure(figsize=(8, 4))
sns.countplot(x='IS_BAD_PAYER', data=df_final, palette='viridis')
plt.title('Distribuição da Variável Alvo: IS_BAD_PAYER')
plt.xlabel('Tipo de Pagador (0: Bom Pagador, 1: Mau Pagador)')
plt.ylabel('Quantidade')
plt.xticks([0, 1], ['Bom Pagador (0)', 'Mau Pagador (1)'])
plt.show()

O gráfico de barras mostra a proporção de clientes classificados como 'bons' e 'maus' pagadores com base nos critérios de atraso de 60 dias ou mais nos últimos 12 meses. Esta visualização é crucial para entender o desbalanceamento de classes e planejar as estratégias de modelagem subsequentes.

In [19]:
# Verificar informações gerais do df_final
print("\nInformações do df_final:")
df_final.info()

Informações do df_final:
<class 'pandas.core.frame.DataFrame'>
Index: 32905 entries, 0 to 36456
Data columns (total 35 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ID                       32905 non-null  int64
 1   CODE_GENDER              32905 non-null  object
 2   FLAG_OWN_CAR             32905 non-null  object
 3   FLAG_OWN_REALTY          32905 non-null  object
 4   CNT_CHILDREN             32905 non-null  int64
 5   AMT_INCOME_TOTAL         32905 non-null  float64
 6   NAME_INCOME_TYPE         32905 non-null  object
 7   NAME_EDUCATION_TYPE      32905 non-null  object
 8   NAME_FAMILY_STATUS       32905 non-null  object
 9   NAME_HOUSING_TYPE        32905 non-null  object
 10  FLAG_MOBIL               32905 non-null  int64
 11  FLAG_WORK_PHONE          32905 non-null  int64
 12  FLAG_PHONE               32905 non-null  int64
 13  FLAG_EMAIL               32905 non-null  int64
 14  OCCUPATION_TYPE          32905 non-null  object
 15  CNT_FAM_MEMBERS          32905 non-null  float64
 16  YEARS_BIRTH              32905 non-null  int64
 17  IS_INACTIVE              32905 non-null  int64
 18  YEARS_EMPLOYED           32905 non-null  int64
 19  TOTAL_MONTHS_OBSERVED    32905 non-null  int64
 20  STATUS_LATED             32905 non-null  int64
 21  STATUS_ON_TIME           32905 non-null  int64
 22  STATUS_NO_CREDIT         32905 non-null  int64
 23  MAX_RISK_SCORE           32905 non-null  int64
 24  TOTAL_MONTHS_RECENT      32905 non-null  float64
 25  STATUS_LATED_RECENT      32905 non-null  float64
 26  STATUS_ON_TIME_RECENT    32905 non-null  float64
 27  STATUS_NO_CREDIT_RECENT  32905 non-null  float64
 28  MAX_RISK_SCORE_RECENT    32905 non-null  float64
 29  TOTAL_MONTHS_OLDER       32905 non-null  float64
 30  STATUS_LATED_OLDER       32905 non-null  float64
 31  STATUS_ON_TIME_OLDER     32905 non-null  float64
 32  STATUS_NO_CREDIT_OLDER   32905 non-null  float64
 33  MAX_RISK_SCORE_OLDER     32905 non-null  float64
 34  IS_BAD_PAYER             32905 non-null  int64
dtypes: float64(12), int64(15), object(8)
memory usage: 9.0+ MB

## 3. Normalização / padronização

**Escolha e justificativa:** _StandardScaler, MinMaxScaler ou nenhum?_

Aplique preferencialmente dentro de um `Pipeline` no notebook 03 — ajustar o scaler antes do split vaza informação do teste para o treino.

**Escolha e Justificativa:** `StandardScaler`

Para este projeto de classificação de risco de crédito, bom ou mau pagador,a escolha foi utilizar o `StandardScaler`. O conjunto de dados apresenta variáveis com magnitudes muito distintas e a presença de alguns outliers foi mantida.

**Justificativas para o `StandardScaler`:**

1.  **Robustez a Outliers:** O `StandardScaler` reescala os dados para que tenham média zero e desvio padrão um. Embora os outliers ainda possam afetar a média e o desvio padrão, o `StandardScaler` é, em geral, **menos sensível a outliers do que o `MinMaxScaler`**. Se usássemos o `MinMaxScaler`, que reescala os dados para um intervalo fixo (e.g., [0,1]) usando os valores mínimos e máximos observados, a presença de outliers extremos poderia comprimir a maioria dos dados em uma faixa muito pequena desse intervalo, diminuindo a variabilidade útil das features. O `StandardScaler`, por não limitar os dados a um intervalo fixo, permite que os outliers mantenham sua distância relativa, o que pode ser benéfico dependendo do algoritmo.

2.  **Generalidade e Ampla Aplicabilidade:** Muitos algoritmos de Machine Learning (como Regressão Linear, Regressão Logística, SVMs, Redes Neurais, K-Means e PCA) funcionam melhor ou convergem mais rapidamente quando as features estão padronizadas para terem média zero e variância unitária.

3.  **Preservação de Informações da Distribuição:** Ao centralizar os dados em zero e escalá-los pela variância, o `StandardScaler` ajuda a mitigar o impacto de diferentes escalas sem distorcer significativamente a forma da distribuição original dos dados (ao contrário de transformações não-lineares, que alteram a distribuição). Isso é importante para algoritmos que se beneficiam da estrutura da distribuição dos dados.

**Por que não `MinMaxScaler`?**

Embora o `MinMaxScaler` seja útil para algoritmos que exigem entradas em um intervalo estritamente definido (como algumas redes neurais com funções de ativação específicas), sua alta sensibilidade a outliers o torna menos ideal neste cenário, onde decidimos manter alguns desses valores extremos. Um único outlier pode distorcer drasticamente a escala, fazendo com que a maioria dos dados fique 'espremida' em uma pequena parte do novo intervalo.

**Implementação no `Pipeline` (Notebook 03):**

Conforme mencionado, é crucial aplicar o `StandardScaler` corretamente para evitar **vazamento de dados (data leakage)**. O processo de 'ajuste' (fit) do scaler (onde ele calcula a média e o desvio padrão) deve ser realizado **exclusivamente no conjunto de dados de treino**. Posteriormente, o scaler 'treinado' será usado para 'transformar' tanto os dados de treino quanto os dados de teste.

Para garantir essa separação rigorosa e automatizar o processo, o `StandardScaler` será integrado a um `Pipeline` no Notebook 03, conforme orientado no enunciado dessa etapa 03. Isso assegura que nenhuma informação do conjunto de teste contamine o processo de reescalonamento, resultando em uma avaliação mais honesta e precisa da performance do modelo.

## 4. Feature engineering


Conforme desenvolvido na etapa anterior de preparação de dados, o conjunto de variáveis preditoras passou por uma transformação estrutural baseada em quebras de janelas temporais. O objetivo principal desta abordagem é permitir que os algoritmos compreendam não apenas o volume acumulado dos eventos, mas também a tendência e a evolução temporal do comportamento de risco dos clientes.A linha do tempo histórica de cada cliente foi segmentada em duas janelas principais:

**Janela Recente (0 a -11 meses)**: Captura a foto mais recente e o comportamento atualizado do tomador de crédito.

**Janela Retrospectiva (Do mês -12 até o fim do período observado)**: Captura o histórico mais antigo.

A partir dessa segmentação temporal, as seguintes métricas foram calculadas duplicando-se os contextos (recent e older), além das suas versões gerais:

'TOTAL_MONTHS_OBSERVED', 'STATUS_LATED', 'STATUS_ON_TIME','STATUS_NO_CREDIT', 'MAX_RISK_SCORE', 'TOTAL_MONTHS_RECENT',
'STATUS_LATED_RECENT', 'STATUS_ON_TIME_RECENT','STATUS_NO_CREDIT_RECENT', 'MAX_RISK_SCORE_RECENT', TOTAL_MONTHS_OLDER', 'STATUS_LATED_OLDER','STATUS_LATED_OLDER',
'STATUS_ON_TIME_OLDER', 'STATUS_NO_CREDIT_OLDER','MAX_RISK_SCORE_OLDER'.

Para enriquecer o modelo e capturar relações mais complexas nos dados, criaremos as seguintes novas features:

INCOME_PER_PERSON (Renda por Pessoa da Família):

Cálculo: AMT_INCOME_TOTAL / CNT_FAM_MEMBERS
Justificativa: A renda total (AMT_INCOME_TOTAL) é um fator importante, mas a capacidade de um indivíduo de honrar seus compromissos financeiros pode ser mais precisamente avaliada ao considerar quantas pessoas dependem dessa renda. Uma renda alta distribuída entre muitos membros da família pode indicar menor folga financeira por indivíduo, enquanto a mesma renda para uma família menor sugere maior capacidade de pagamento. Esta feature normaliza a renda pelo tamanho da família, oferecendo uma perspectiva de renda per capita que pode ser um indicador mais robusto de estabilidade financeira e risco de crédito.

HAS_CHILDREN (Possui Filhos):

Cálculo: Binário (1 se CNT_CHILDREN > 0, 0 caso contrário)
Justificativa: A presença de filhos (CNT_CHILDREN > 0) pode influenciar significativamente as responsabilidades financeiras de um indivíduo. Famílias com filhos geralmente têm despesas mais elevadas, o que pode impactar sua capacidade de pagamento de dívidas. Embora CNT_CHILDREN já exista, uma feature binária explícita pode simplificar a interpretação para alguns modelos e destacar a diferença fundamental entre ter ou não ter filhos, independentemente do número exato de crianças.

In [21]:
# Criar features de proporção de histórico de crédito
df_final['INCOME_PER_PERSON'] = df_final['AMT_INCOME_TOTAL'] / df_final['CNT_FAM_MEMBERS']
df_final['HAS_CHILDREN'] = (df_final['CNT_CHILDREN'] > 0).astype(int)

In [22]:
df_final.head()

,ID,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,FLAG_MOBIL,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,YEARS_BIRTH,IS_INACTIVE,YEARS_EMPLOYED,TOTAL_MONTHS_OBSERVED,STATUS_LATED,STATUS_ON_TIME,STATUS_NO_CREDIT,MAX_RISK_SCORE,TOTAL_MONTHS_RECENT,STATUS_LATED_RECENT,STATUS_ON_TIME_RECENT,STATUS_NO_CREDIT_RECENT,MAX_RISK_SCORE_RECENT,TOTAL_MONTHS_OLDER,STATUS_LATED_OLDER,STATUS_ON_TIME_OLDER,STATUS_NO_CREDIT_OLDER,MAX_RISK_SCORE_OLDER,IS_BAD_PAYER,INCOME_PER_PERSON,HAS_CHILDREN
0,5008804,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,1,1,0,0,Unknown,2.0,32,0,12,16,2,13,1,2,12.0,0.0,12.0,0.0,0.0,4.0,2.0,1.0,1.0,2.0,0,213750.0,0
1,5008805,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,1,1,0,0,Unknown,2.0,32,0,12,15,2,12,1,2,12.0,0.0,12.0,0.0,0.0,3.0,2.0,0.0,1.0,2.0,0,213750.0,0
2,5008806,M,Y,Y,0,112500.0,Working,Secondary / secondary special,Married,House / apartment,1,0,0,0,Security staff,2.0,58,0,3,30,7,7,16,1,12.0,3.0,7.0,2.0,1.0,18.0,4.0,0.0,14.0,1.0,0,56250.0,0
3,5008808,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,1,0,1,1,Sales staff,1.0,52,0,8,5,2,0,3,1,5.0,2.0,0.0,3.0,1.0,0.0,0.0,0.0,0.0,-2.0,0,270000.0,0
4,5008809,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,1,0,1,1,Sales staff,1.0,52,0,8,5,0,0,5,-1,0.0,0.0,0.0,0.0,-2.0,5.0,0.0,0.0,5.0,-1.0,0,270000.0,0

Tratamento de Variáveis Categóricas

Para preparar os dados para modelagem, é necessário converter as variáveis categóricas para um formato numérico. Serão aplicadas as seguintes estratégias:

*   **Variáveis Categóricas Binárias:** Mapeadas diretamente para 0 e 1, criando novas colunas para as versões codificadas.
*   **Variáveis Categóricas Não-Binárias:** Utilizado One-Hot Encoding para criar novas colunas binárias para cada categoria, evitando a criação de uma ordem artificial entre as categorias.

In [23]:
# Fazer uma cópia do Dataframe.
df_processed = df_final.copy()

# Mapear variáveis categóricas binárias para numéricas.
df_processed["CODE_GENDER"] = df_processed["CODE_GENDER"].map({"M": 1, "F": 0})
df_processed["FLAG_OWN_CAR"] = df_processed["FLAG_OWN_CAR"].map({"Y": 1, "N": 0})
df_processed["FLAG_OWN_REALTY"] = df_processed["FLAG_OWN_REALTY"].map({"Y": 1, "N": 0})

# Identificar colunas categóricas restantes que não são binárias para One-Hot Encoding
categorical_cols_to_encode = [
    'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS',
    'NAME_HOUSING_TYPE', 'OCCUPATION_TYPE'
]

# Aplicar One-Hot Encoding para as variáveis categóricas restantes
# e juntar as colunas codificadas ao df_processed, removendo as colunas originais.
df_final_encoded = pd.get_dummies(df_processed, columns=categorical_cols_to_encode, prefix=categorical_cols_to_encode, drop_first=True)

#Remover a coluna 'ID' já que não é relevante para a previsão,
#pois é apenas um identificador único.
df_final_encoded = df_final_encoded.drop(columns=['ID'])
print("df_final_encoded após o tratamento das variáveis categóricas:")
display(df_final_encoded.head())

df_final_encoded após o tratamento das variáveis categóricas:

,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,FLAG_MOBIL,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,CNT_FAM_MEMBERS,YEARS_BIRTH,IS_INACTIVE,YEARS_EMPLOYED,TOTAL_MONTHS_OBSERVED,STATUS_LATED,STATUS_ON_TIME,STATUS_NO_CREDIT,MAX_RISK_SCORE,TOTAL_MONTHS_RECENT,STATUS_LATED_RECENT,STATUS_ON_TIME_RECENT,STATUS_NO_CREDIT_RECENT,MAX_RISK_SCORE_RECENT,TOTAL_MONTHS_OLDER,STATUS_LATED_OLDER,STATUS_ON_TIME_OLDER,STATUS_NO_CREDIT_OLDER,MAX_RISK_SCORE_OLDER,IS_BAD_PAYER,INCOME_PER_PERSON,HAS_CHILDREN,NAME_INCOME_TYPE_Pensioner,NAME_INCOME_TYPE_State servant,NAME_INCOME_TYPE_Student,NAME_INCOME_TYPE_Working,NAME_EDUCATION_TYPE_Higher education,NAME_EDUCATION_TYPE_Incomplete higher,NAME_EDUCATION_TYPE_Lower secondary,NAME_EDUCATION_TYPE_Secondary / secondary special,NAME_FAMILY_STATUS_Married,NAME_FAMILY_STATUS_Separated,NAME_FAMILY_STATUS_Single / not married,NAME_FAMILY_STATUS_Widow,NAME_HOUSING_TYPE_House / apartment,NAME_HOUSING_TYPE_Municipal apartment,NAME_HOUSING_TYPE_Office apartment,NAME_HOUSING_TYPE_Rented apartment,NAME_HOUSING_TYPE_With parents,OCCUPATION_TYPE_Cleaning staff,OCCUPATION_TYPE_Cooking staff,OCCUPATION_TYPE_Core staff,OCCUPATION_TYPE_Drivers,OCCUPATION_TYPE_HR staff,OCCUPATION_TYPE_High skill tech staff,OCCUPATION_TYPE_IT staff,OCCUPATION_TYPE_Laborers,OCCUPATION_TYPE_Low-skill Laborers,OCCUPATION_TYPE_Managers,OCCUPATION_TYPE_Medicine staff,OCCUPATION_TYPE_Private service staff,OCCUPATION_TYPE_Realty agents,OCCUPATION_TYPE_Sales staff,OCCUPATION_TYPE_Secretaries,OCCUPATION_TYPE_Security staff,OCCUPATION_TYPE_Unknown,OCCUPATION_TYPE_Waiters/barmen staff
0,1,1,1,0,427500.0,1,1,0,0,2.0,32,0,12,16,2,13,1,2,12.0,0.0,12.0,0.0,0.0,4.0,2.0,1.0,1.0,2.0,0,213750.0,0,False,False,False,True,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
1,1,1,1,0,427500.0,1,1,0,0,2.0,32,0,12,15,2,12,1,2,12.0,0.0,12.0,0.0,0.0,3.0,2.0,0.0,1.0,2.0,0,213750.0,0,False,False,False,True,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
2,1,1,1,0,112500.0,1,0,0,0,2.0,58,0,3,30,7,7,16,1,12.0,3.0,7.0,2.0,1.0,18.0,4.0,0.0,14.0,1.0,0,56250.0,0,False,False,False,True,False,False,False,True,True,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
3,0,0,1,0,270000.0,1,0,1,1,1.0,52,0,8,5,2,0,3,1,5.0,2.0,0.0,3.0,1.0,0.0,0.0,0.0,0.0,-2.0,0,270000.0,0,False,False,False,False,False,False,False,True,False,False,True,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
4,0,0,1,0,270000.0,1,0,1,1,1.0,52,0,8,5,0,0,5,-1,0.0,0.0,0.0,0.0,-2.0,5.0,0.0,0.0,5.0,-1.0,0,270000.0,0,False,False,False,False,False,False,False,True,False,False,True,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False

Considerações Finais sobre Pré-processamento: Outliers e Balanceamento de Classes

É importante ressaltar que, nesta etapa de pré-processamento (Notebook 02), algumas técnicas comuns não foram aplicadas, especificamente:

*   **Tratamento de Outliers (Capping):** A decisão de não aplicar o capping para outliers neste momento é estratégica. Embora a presença de valores extremos possa influenciar alguns modelos, a remoção ou transformação precoce de outliers pode levar à perda de informações valiosas ou à criação de um viés artificial, especialmente antes da divisão dos dados em conjuntos de treino e teste. Além disso, a aplicação de técnicas de capping é mais robusta quando realizada dentro de um `Pipeline` de pré-processamento no notebook 03, garantindo que o ajuste dos limites de capping ocorra apenas nos dados de treino, evitando assim o **vazamento de dados (data leakage)** do conjunto de teste. (Obs.: os outliers foram tratados na etapa "04 Outliers" do notebook 01, para responder tal tópico do trabalho, porém os códigos não foram trazidos para esse notebook 02.)  

*   **Balanceamento de Classes:** O conjunto de dados apresenta um desequilíbrio de classes significativo para a variável alvo `IS_BAD_PAYER`, conforme observado na seção de definição da variável alvo. No entanto, o balanceamento de classes (usando técnicas como oversampling, undersampling ou SMOTE) não foi realizado nesta fase. A principal razão para isso é evitar o **vazamento de dados**. Técnicas de balanceamento, especialmente oversampling, criam novas amostras baseadas nos dados existentes. Se aplicadas antes da divisão treino-teste, as amostras sintéticas criadas podem "ver" informações do conjunto de teste, levando a uma superestimação da performance do modelo.

Ambas as medidas — o tratamento de outliers (se considerado necessário após análise mais aprofundada) e o balanceamento de classes — serão consideradas e implementadas no **Notebook 03**, dentro de um `Pipeline` de pré-processamento. Isso garantirá que todas as transformações de dados sejam aplicadas de maneira apropriada, prevenindo o vazamento de informações e resultando em uma avaliação de modelo mais justa e confiável.

## 5. Salvar dataset tratado

In [30]:
PROCESSED.mkdir(parents=True, exist_ok=True)
df_final_encoded.to_csv(PROCESSED / "dataset_tratado.csv", index=False)